[package]
authors = ["The Rust Project Developers"]
name = "syntax_pos"
version = "0.0.0"

[lib]
name = "syntax_pos"
path = "lib.rs"
crate-type = ["dylib"]

[dependencies]
serialize = { path = "../libserialize" }
rustc_data_structures = { path = "../librustc_data_structures" }
arena = { path = "../libarena" }
scoped-tls = { version = "0.1.1", features = ["nightly"] }
serde = "1.0"
serde_derive = "1.0"
unicode-width = "0.1.4"
cfg-if = "0.1.2"
